#Fonts
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 13.0

#: The enabled window layouts. A comma separated list of layout names.
#: The special value all means all layouts. The first listed layout
#: will be used as the startup layout. Default configuration is all
#: layouts in alphabetical order. For a list of available layouts, see
#: the https://sw.kovidgoyal.net/kitty/overview/#layouts.

enabled_layouts all

window_resize_step_cells 2
window_resize_step_lines 2

#: The step size (in units of cell width/cell height) to use when
#: resizing kitty windows in a layout with the keyboard
#: (start_resizing_window). The cells value is used for horizontal
#: resizing and the lines value for vertical resizing.

single_window_margin_width -1
draw_minimal_borders yes
placement_strategy center
visual_window_select_characters 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
scrollback_lines 2000
wheel_scroll_min_lines 3
window_padding_width 5
hide_window_decorations no
sync_to_monitor yes
background_opacity 1
background_blur 1
dynamic_background_opacity yes

#background_image /home/onnoy/Picture/wallpaper/1337162.png
#background_image_layout cscaled
#background_tint 0.97

#: The list of characters to use for visual window selection (for
#: example for selecting a window to focus with focus_visible_window).
#: The value should be a series of unique numbers or alphabets, case
#: insensitive, from the set [0-9A-Z]. Specify your preference as a
#: string of characters.

# with Shell integration enabled, using negative values means windows sitting at a shell prompt are not counted,
# only windows where some command is currently running.
# see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.confirm_os_window_close
confirm_os_window_close 0

#URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
# active_border_color     #00ff00
# inactive_border_color   #cccccc
# bell_border_color       #ff5a00

# OS Window titlebar colors
# wayland_titlebar_color #CDD6F4
# macos_titlebar_color system

# Tab bar colors
# active_tab_foreground   #11111B
# active_tab_background   #b4befe
# inactive_tab_foreground #CDD6F4
# inactive_tab_background #181825
# tab_bar_background      #11111B

#tab_bar_min_tabs 1
#tab_bar_edge top
#: tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
tab_bar_margin_height 0.0 0.0
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style powerline
tab_bar_align left
tab_powerline_style slanted
tab_activity_symbol 

#: kitty mod key
kitty_mod ctrl+shift

#: Special modifier key alias for default shortcuts. You can change
#: the value of this option to alter all default shortcuts that use
#: kitty_mod.

# map kitty_mod+t new_tab
map ctrl+shift+t new_tab

#: Next tab
map ctrl+tab next_tab

#: Previous tab
map ctrl+shift+tab previous_tab

#: Close tab
map kitty_mod+q close_tab

allow_hyperlinks yes

# BEGIN_KITTY_THEME
include themes/Decay-Green.conf
# END_KITTY_THEME
