[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
position = "17% 5%"
size = "65% 60%"
offset = "200%"

[scratchpads.music]
animation = "fromBottom"
command = "kitty --class kitty-pulsemixer -e pulsemixer"
class = "kitty-pulsemixer"
size = "50% 20%"
offset = "200%"

[scratchpads.taskbar]
animation = "fromTop"
command = "kitty --class kitty-taskbar -e htop"
class = "kitty-taskbar"
size = "65% 65%"
offset = "200%"
