[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
linemode       = "size"
show_hidden    = true
[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
brave = [
    { run = '"brave" "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
