[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
linemode       = "size"
show_hidden    = true
[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\vlc.exe" %*', orphan = true, for = "windows" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
# ...
